#!/usr/bin/lua
 
local menu = {}
for i, page in ipairs(arg) do
   menu[i] = "<a href=" .. page .. ".html>" .. page:gsub("_", " ") .. "</a>"
end
menu = table.concat(menu, " | ")
 

function code(s)
	local fname = os.tmpname()
   local fd = io.open(fname, "w")
   fd:write(s)
   fd:close()
 
   local h = io.popen("highlight --fragment --css=/dev/null --syntax lua " .. fname, "r")
   local v = h:read("*a")
   h:close()
 
   return "<pre class=hl>" .. v .. "</pre>\n\n"
end
 
function link(s)
	if s:find("png") then
		return "<img src='img/" .. s .. "'>"
	else
		local u = s
		if not u:find("%.%a+$") then u = u .. ".html" end
		return "<a href=" .. u .. ">" .. s .. "</a>"
	end
end

function list(s, n)
	return "<ul>" .. s:gsub("\n%*", "<li>") .. "</ul>\n\n" .. n
end

local toc = {}

function h1(s)
	table.insert(toc, s)
	return "<a name='" .. s .. "'></a><h1>" .. s .. "</h1>"
end

function h2(s)
	table.insert(toc, s)
	return "<a name='" .. s .. "'></a><h2>" .. s .. "</h2>"
end

local c = io.read("*a")

c = c:gsub("<", "&lt;")
c = c:gsub(">", "&gt;")
c = c:gsub("'(%w+)'", "<i>%1</i>")
c = c:gsub("_(%w+)_", "<b>%1</b>")
c = c:gsub("\n= ([^\n]+)", h1)
c = c:gsub("\n== ([^\n]+)", h2)
c = c:gsub("\n(\n .-)\n\n", code)
c = c:gsub("%[([%S+]+)%]", link)
c = c:gsub("NOTE: (.-)\n\n", "<div class=warn>%1</div>\n\n")
c = c:gsub("(\n%*.-)\n([^%s%*])", list)
c = c:gsub("\n\n", "\n\n<p>\n")

for i = 1, #toc do
	local s = toc[i]
	toc[i] = "<a href='#" .. s .. "'>" .. s .. "</a>"
end
toc = table.concat(toc, "<br>")
 
print([[
<!DOCTYPE html>
<head>
   <link rel="stylesheet" type="text/css" href="style.css">
   <link rel="stylesheet" type="text/css" href="highlight.css">
   <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Text Me One">
   <link rel="icon" type="image/png" href="img/worp-icon.png" />
</head>
 
<body>
	<div id=logo></div>
 
	<div id=menu>
]] .. menu .. [[
   </div>
	<table id=tocmain>
		<tr>
			<td>
				<div id=toc>
				<p>
]] .. toc .. [[
				</div>
			</td><td>
				<div id=main>
]] .. c .. [[
				</div>
			</td>
		</tr>
	</table>
	</div>
</body>
]])
 

-- vi: ft=lua ts=3 sw=3
